import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {__DEV__} from "@apollo/client/utilities/globals";
import {loadDevMessages, loadErrorMessages} from "@apollo/client/dev";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

if (__DEV__) {  // Adds messages only in a dev environment
    loadDevMessages();
    loadErrorMessages();
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    )
}
